import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar";
import AuthContext from "../context/AuthContext";
const openSans = Open_Sans({ subsets: ["latin"] });
import React from "react";
import SWRConfigContext from "@/context/SWRConfigContext";

export const metadata: Metadata = {
  title: "Instagram",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={openSans.className}>
      <body className="w-full max-w-screen-2xl mx-auto">
        <AuthContext>
          <header className="sticky top-0 bg-white z-10 rounded-2xl">
            <NavBar />
          </header>
          <main>
            <SWRConfigContext>{children}</SWRConfigContext>
          </main>
        </AuthContext>
      </body>
    </html>
  );
}
